### PR TITLE
Feature/171 move buttons

### LINKED ISSUE #171: Move The Key and Refresh buttons to the right of the Icons
**Is your feature request related to a problem? Please describe.**
When I display a bundle with no Title or Description, The Key button and Refresh button take up too much vertical space. 

**Describe the solution you'd like**
I'd like The Key and Refresh buttons to be in line with the Icons.

**Describe alternatives you've considered**
As discussed in #137 we could have a setting to say show the buttons at the top or the bottom, but if that was the case I would still like to hide the buttons as I would like  the icons to display with similar vertical space above and below if there is no Title or Description.

### PR DESCRIPTION
**Pull request by JodieM**
# Changes
* Changed the layout of the buttons so they can be displayed in the same top right hand corner if there is full title and description, no title, no description or no title or description. 
* Changed the buttons to be `base` style to match the other buttons on the page. 
* Changed the icon spacing in the heading to more closely match standard

# Issues Closed
#171 

# Testing
https://docs.google.com/document/d/12S4hkygtQndvVoywhDO1qMrapMOH0h1uFafObdcY8yY/edit?usp=sharing

# Code Run Through
https://www.loom.com/share/7129fae1c7674025a1efbac0ae90da68?sid=eb6b991f-6930-490b-a935-85e8d680c3cf (there have been a few changes since then, but way the code has changed to be an Aricle rather than a Card is still the same).

### CODE REVIEW

**Comment by JodieM** [comment]
I need to make some more changes and include Dynamic Forms in this.

**Comment by JodieM** [comment]
@tschug I tried to get this code re-worked ready for a revised PR tonight, but I got stuck with some JS errors. 
Can you please help when you have some time? Not urgent. 

The latest Commit https://github.com/SFDO-Community/Salesforce-Indicators/commit/341da22ba400dc175cd22ac82e4c07623ff66ed7 has the issue when adding custom colours to the Bundle Icon. 

https://www.loom.com/share/f4378bb4930845f19a2736d22bcf18c6?sid=c250375d-8e7c-4305-9df4-9aaf8c88ae39

**Comment by tschug** [comment]
I definitely think it's in the area you've shown and related to the change.

It looks like there's a few types of changes in that area, and I think the issue is what the error says --- I cannot find a "style" - which is likely what was there when it was in the <template> tag.

It could be a few things:
* Moving from a Lightning Card to an HTML Article (My primary suspect)
* How it's loading since the `hasHeader` variable is no longer there and I don't know if it's replacement meets the same conditions.
* We may need to also look at WHICH scenario is throwing the issue since your demo has both on the same page, and I think it's very possible it.

The last point, the `var css = this.template.querySelector(".cardIcon").style;` is being called by the method `initCSSVariables()` and that's called by the `renderedCallback()`.  And so, it's possible that because there is no `cardIcon` on the page, it's throwing the error that it cannot be found, since it's in a nested set of IFs
```
<article class="slds-card">
                <template lwc:if={isStandardUsage}>
                    <template lwc:if={showTitle}>
                        <div class="cardIcon">
```
And based on the first IF block - it's only applicable to the `isStandardUsage` --- so it should be there.  But it won't be there for your dynamic form scenario.

I'll look more later, but those are my suspicions.

**Comment by JodieM** [comment]
Ready to review now @tschug. I still like this, but am aware that changing to an Article might be a bit of a step too far.

**Review by tschug — APPROVED** [review]

**Pull request merged**
